"use strict";

module.exports = {
	SET_DARKMODE:'SET_DARKMODE',
	RESET_OPEN:'RESET_OPEN',
	OPEN_SEARCH:'OPEN_SEARCH',
	OPEN_NOTIFICATION:'OPEN_NOTIFICATION',
	OPEN_NOTIFICATION_M:'OPEN_NOTIFICATION_M',
	OPEN_USER:'OPEN_USER',
	OPEN_USER_M:'OPEN_USER_M',
	OPEN_MODAL:'OPEN_MODAL',
	SET_USER:'SET_USER',
	VERIFY_OTP:'VERIFY_OTP',
	LOGOUT:'LOGOUT',
	OPEN_WELCOME: 'OPEN_WELCOME',
	OPEN_QUESTION: 'OPEN_QUESTION',
	OPEN_RANKING: 'OPEN_RANKING',
	OPEN_FINISH: 'OPEN_FINISH',
	JOIN_GAME: 'JOIN_GAME',
	SET_QUESTIONS: 'SET_QUESTIONS',
	OPEN_CONGRAT: 'OPEN_CONGRAT',
	OPEN_FINISH: 'OPEN_FINISH',
	SET_ANSWER: 'SET_ANSWER',
	OPEN_APPLY:'OPEN_APPLY',
	SET_STATUS:'SET_STATUS',
	RESET_STATUS:'RESET_STATUS'
}